% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=2.5cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Factores asociados al rebrote de miasis por Cochliomyia hominivorax en Chiapas: Un enfoque de modelaje de la enfermedad.},
  pdfauthor={Estrella Segobia, Blanca Osornio, Daniela Villanueva, Melissa Martinez},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Factores asociados al rebrote de miasis por Cochliomyia
hominivorax en Chiapas: Un enfoque de modelaje de la enfermedad.}
\author{Estrella Segobia, Blanca Osornio, Daniela Villanueva, Melissa
Martinez}
\date{2025-11-24}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Introducción}\label{introducciuxf3n}

La reemergencia de la miasis por \emph{Cochliomyia hominivorax} en
México durante 2024 evidenció la necesidad de herramientas analíticas
que permitan comprender la dinámica que favorece su persistencia en
sistemas ganaderos. Como extensión del proyecto original presentado en
la materia \texttt{proyecto\ de\ investigación}, la presente sección se
enfoca exclusivamente en la construcción, calibración y validación de un
modelo compartimental. Este modelo busca integrar parámetros biológicos,
climáticos y socioeconómicos asociados al rebrote registrado en el
estado de Chiapas, con el fin de identificar los factores que
contribuyeron a su aparición y mantenimiento.

Los modelos compartimentales permiten descomponer procesos complejos en
transiciones ordenadas entre estados epidemiológicos. Para \emph{C.
hominivorax}, esta aproximación resulta adecuada debido a que su ciclo
incluye etapas definidas que pueden representarse mediante
compartimentos susceptibles, expuestos, infestados y recuperados. A
diferencia de las simulaciones centradas en la TIE (Técnica del Insecto
Estéril) o modelos climáticos aislados, esta propuesta integra múltiples
componentes para generar un panorama mayor de la dinámica observada.

\section{Antecedentes}\label{antecedentes}

La literatura existente documenta modelos enfocados principalmente en
evaluar estrategias de liberación de machos estériles (Dhahbi et al.,
2020) y modelos ecofisiológicos que analizan el efecto del clima sobre
la distribución del parásito (Gutiérrez et al., 2019). Sin embargo, no
se han encontrado modelos que incorporen lo siguiente:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Ciclo de vida del parásito.
\item
  Datos climáticos (humedad, precipitación y temperatura)
\item
  Componentes socioeconómicos (entrada legal e ilegal de ganado)
\end{enumerate}

Por ello, se plantea el desarrollo de un modelo SEIRS expandido que
capture las transiciones biológicas del gusano, su interacción con
factores ambientales y socioeconomicos.

\section{Objetivos}\label{objetivos}

\subsection{Objetivo general}\label{objetivo-general}

Desarrollar y validar un modelo epidemiológico SEIRS expandido que
represente la dinámica del rebrote de miasis por \emph{C. hominivorax}
en Chiapas, integrando parámetros biológicos, climáticos y
socioeconómicos.

\subsection{Objetivos específicos}\label{objetivos-especuxedficos}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Construir un modelo compartimental SEIRS que represente la dinámica de
  infestación en ganado bovino.
\item
  Obtener y depurar parámetros biológicos y ambientales mediante
  revisión documental y bases oficiales.
\item
  Implementar análisis de sensibilidad local y global utilizando
  muestreo tipo Latin Hypercube e índices de Sobol.
\item
  Simular escenarios antes, durante y después del rebrote a fin de
  identificar los parámetros con mayor influencia en la dinámica
  observada.
\end{enumerate}

\section{Metodología}\label{metodologuxeda}

\subsection{Integración y curación de bases de
datos}\label{integraciuxf3n-y-curaciuxf3n-de-bases-de-datos}

La información se recopilará desde fuentes oficiales y científicas,
incluyendo:

\begin{itemize}
\item
  SENASICA/SADER: número de casos confirmados y sus fechas.
\item
  INEGI: ingreso de ganado.
\item
  USDA/COMEXA: frecuencia y volumen de liberaciones de machos estériles.
\item
  CONAGUA: registros de precipitación, humedad relativa y temperatura.
\item
  \textbf{Además de referencias como:}

  \textbf{(ingresar bibliografía de dónde se sacan tasas sobre el ciclo
  de vida de la larva) Literatura especializada: tasas biológicas
  (oviposición, maduración larvaria, pupación, emergencia y
  longevidad).}
\end{itemize}

\subsection{Formulación del modelo SEIRS
expandido}\label{formulaciuxf3n-del-modelo-seirs-expandido}

El modelo propuesto describe la dinámica epidemiológica de la miasis por
\emph{Cochliomyia hominivorax} en bovinos mediante un esquema
compartimental tipo SEIRS. El flujo básico considera cuatro estados:

\[
S \rightarrow E \rightarrow I \rightarrow R \rightarrow S
\]

donde:

\begin{itemize}
\tightlist
\item
  \textbf{S}: bovinos susceptibles.
\item
  \textbf{E}: bovinos expuestos (oviposición o presencia temprana de
  larvas).
\item
  \textbf{I}: bovinos infestados (lesiones con larvas activas).
\item
  \textbf{R}: bovinos recuperados temporalmente (lesiones tratadas o
  cicatrizadas).
\end{itemize}

El retorno \(R \rightarrow S\) representa la \textbf{pérdida de
protección}, la \textbf{generación de nuevas heridas}, o el
\textbf{reinicio del riesgo} tras la curación.

Además del ciclo SEIRS en bovinos, se incorpora explícitamente el ciclo
biológico del gusano barrenador:

\[
A \rightarrow H \rightarrow L \rightarrow P
\]

con:

\begin{itemize}
\tightlist
\item
  \textbf{A} = adultos (moscas reproductivas)
\item
  \textbf{H} = huevos
\item
  \textbf{L} = larvas
\item
  \textbf{P} = pupas
\end{itemize}

Estos dos subsistemas se acoplan mediante la \textbf{fuerza de
infestación}, que depende del número de adultos y del clima.

\subsubsection{Módulos adicionales del
modelo}\label{muxf3dulos-adicionales-del-modelo}

A continuación se describen los tres módulos que complementan el modelo
SEIRS y que permiten incorporar mejor las condiciones reales del
rebrote.

\subsubsection{\texorpdfstring{\textbf{Módulo
climático}}{Módulo climático}}\label{muxf3dulo-climuxe1tico}

El desarrollo del gusano barrenador depende mucho del clima. Para que
pase de huevo → larva → pupa → adulto, necesita buena temperatura,
suficiente humedad y lluvia.\\
Por eso, cada parámetro del ciclo biológico
(\(\alpha, \eta, \kappa, \epsilon\)) se ajusta con una función que nos
dice \textbf{qué tan favorable es el clima} en ese momento.

La función combina temperatura (T), precipitación (P) y humedad (H):

\[
f_c(T, P, H) = 
\left( \frac{T - T_{min}}{K} \right)
\left( \frac{P - P_{min}}{K} \right)
\left( \frac{H - H_{min}}{K} \right)
\]

\begin{itemize}
\tightlist
\item
  Si el clima está ``ideal'', la función da valores grandes y el gusano
  se desarrolla rápido.
\item
  Si el clima está ``malo'', los valores bajan y el desarrollo se frena.
\end{itemize}

Este factor se multiplica directamente en tus parámetros de paso:

\begin{itemize}
\tightlist
\item
  \(\alpha\) : oviposición ajustada
\item
  \(\eta\) : paso huevo → larva
\item
  \(\kappa\) : paso larva → pupa
\item
  \(\epsilon\) : paso pupa → adulto
\end{itemize}

Así el modelo reacciona automáticamente a las condiciones reales.

\subsubsection{\texorpdfstring{\textbf{Módulo
socioeconómico}}{Módulo socioeconómico}}\label{muxf3dulo-socioeconuxf3mico}

Además del clima, la entrada de animales al estado afecta la dinámica de
la miasis. Aquí se consideran dos tipos:

\begin{itemize}
\tightlist
\item
  \textbf{entrada legal}, que aumenta bovinos susceptibles registrados,
\item
  \textbf{entrada ilegal}, que puede mover casos entre municipios sin
  registros oficiales.
\end{itemize}

Como no podemos medir exactamente cuánto ganado ilegal entra, usamos un
ajuste sencillo:

\[
\rho = \frac{\text{incautaciones}}{\text{estimación total}}
\]

Este ajuste representa el nivel de ganado ilegal que pudo entrar. Lo
cual influye directamente en:

\begin{itemize}
\tightlist
\item
  la cantidad de bovinos susceptibles \(S\)
\item
  la posibilidad de introducir animales infestados
\item
  y el mantenimiento del riesgo durante el rebrote
\end{itemize}

\subsubsection{Módulo de mitigación}\label{muxf3dulo-de-mitigaciuxf3n}

Este módulo representa la \textbf{Técnica del Insecto Estéril (TIE)},
que disminuye la reproducción del gusano.

Cuando se liberan machos estériles, compiten con los machos normales,
pero si una hembra se aparea con un macho estéril, los huevos no son
viables.\\
En el modelo esto se ajusta modificando la oviposición real:

\[
\alpha_{ef} = \alpha (1 - u)
\]

donde:

\begin{itemize}
\tightlist
\item
  \(u\) = proporción de hembras que sí fueron fecundadas por machos
  estériles.
\end{itemize}

Entre mayor sea \(u\), menor es la oviposición efectiva, y por lo tanto,
disminuye la producción de larvas.

Este módulo permite simular escenarios con liberaciones bajas, medias o
intensivas.

\pandocbounded{\includegraphics[keepaspectratio]{images/Captura de pantalla 2025-11-23 152313.png}}

\textbf{A continuación se presenta la formulación del modelo completo
mediante ecuaciones diferenciales:}

La población total del hospedero es:

\[
N_v = S_v + E_v + I_v + R_v
\]

\textbf{Ecuaciones para el hospedero}

--\textgreater{} Susceptibles

\[
\frac{dS_v}{dt}
= \text{natalidad} + p_1 + p_2
  - \sigma S_v \left(\frac{M}{N_v}\right)
  - \mu_v S_v
  + \theta R_v
\]

--\textgreater{} Expuestos

\[
\frac{dE_v}{dt}
= \sigma S_v \left(\frac{M}{N_v}\right)
  - \beta E_v
  - \mu_v E_v
\]

--\textgreater{} Infestados

\[
\frac{dI_v}{dt}
= \sigma S_v \left(\frac{M}{N_v}\right)
  - \beta E_v
  - \gamma I_v
  + \delta M_l I_v
  - \mu_v I_v
\] --\textgreater{} Recuperados

\[
\frac{dR_v}{dt}
= \gamma I_v
  - \mu_v R_v
  - \theta R_v
\]

\textbf{Ciclo del gusano barrenador}

--\textgreater{} Adultos

\[
\frac{dM}{dt}
= \epsilon M_p
  - \alpha M
  - \mu_m M
\]

--\textgreater{} Huevos

\[
\frac{dM_o}{dt}
= \alpha M
  - (\eta + \mu_m) M_o
\]

--\textgreater{} Larvas

\[
\frac{dM_l}{dt}
= \eta M_o
  - (\kappa + \mu_m) M_l
\]

--\textgreater{} Pupas

\[
\frac{dM_p}{dt}
= \kappa M_l
  - (\epsilon + \mu_m) M_p
\]

\subsubsection{Obtención de
Parámetros}\label{obtenciuxf3n-de-paruxe1metros}

Estos se basan en la biología conocida de la mosca \emph{Cochliomyia
hominivorax} y se obtienen principalmente de literatura científica,
estudios entomológicos y reportes de programas de erradicación (como el
de COPEG o agencias gubernamentales como SENASICA/USDA). La siguiente
información se obtuvo de SENASICA (2020):

\begin{itemize}
\tightlist
\item
  El parámetro \(\alpha_{\text{base}}\) representa la tasa promedio de
  producción de huevos por mosca adulta por día en condiciones
  ideales.\[\alpha_{\text{base}} = \frac{\text{Huevos totales puestos en su vida}}{\text{Esperanza de vida reproductiva de la hembra (días)}}\]
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Dato Biológico}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Valor}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Uso en} \(\alpha_{\text{base}}\)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Población en \(A\) & 50\% Hembras, 50\% Machos & Solo las hembras
oviponen. \\
Oviposición por Masa & \(200\) a \(400\) huevos (Usamos \(300\)) & Se
usa para calcular la producción total. \\
Masas Totales & Hasta cuatro masas de huevos en su vida. & Se usa para
calcular la producción total. \\
Vida Reproductiva & El apareamiento ocurre entre el día 3-5, y la
oviposición comienza al día 6. La vida es de \(\approx 20\) días. & La
fase reproductiva dura aproximadamente \(20 - 6 = 14\) días. \\
\end{longtable}

Valor que usaremos para el modelo: \(\alpha_{\text{base}} \approx 43\)
por día.

\textbf{Ajuste de la fecundidad por Técnica del Insecto Estéril (TIE)}

Para estimar cuánto baja la reproducción por las liberaciones de machos
estériles, usamos el parámetro \textbf{u}, que representa la proporción
de hembras silvestres que quedan esterilizadas al aparearse con machos
estériles.

La fórmula estándar de la TIE es:

\[ u=\frac{CS}{CS+W} \]

donde: - \(S\): machos estériles liberados por día, - \(W\): machos
silvestres, - \(C\): competitividad del macho estéril.

La competitividad \(C\) se usa porque el macho estéril no siempre
compite igual que el silvestre: a veces vuela menos, vive menos o es
menos atractivo. Por eso no basta con contar moscas; hay que ponderar su
``calidad''. Se tomo \(C=0.5\) como valor medio estimado para \emph{C.
hominivorax}, ya que especificamente de esta mosca, no hay registros,
sin embrago basado en la literatura de otros vectores, ronda entre 0.3 y
0.7, por lo que es el promedio.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{C }\OtherTok{\textless{}{-}} \FloatTok{0.5}                   \CommentTok{\# competitividad promedio}
\end{Highlighting}
\end{Shaded}

Con los datos de SENASICA (885 millones de moscas estériles entre nov
2024 y mayo 2025)
(\url{https://www.gob.mx/agricultura/articulos/tecnica-del-insecto-esteril-la-tecnologia-que-esta-aplicando-el-gobierno-de-mexico-contra-el-gusano-barrenador-del-ganado}),
el promedio diario fue:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lib\_tot }\OtherTok{\textless{}{-}} \FloatTok{885e6}
\NormalTok{dias }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.Date}\NormalTok{(}\StringTok{"2025{-}05{-}16"}\NormalTok{) }\SpecialCharTok{{-}} \FunctionTok{as.Date}\NormalTok{(}\StringTok{"2024{-}11{-}30"}\NormalTok{))}

\NormalTok{S }\OtherTok{\textless{}{-}}\NormalTok{ lib\_tot }\SpecialCharTok{/}\NormalTok{ dias        }\CommentTok{\# estériles por día}
\NormalTok{S}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5299401
\end{verbatim}

y, dado que el programa opera con una relación 10 moscas esteriles por 1
silvestre (\url{https://www.copeg.org/gusano-barrenador/\#insecto}):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{W }\OtherTok{\textless{}{-}}\NormalTok{ S}\SpecialCharTok{/}\DecValTok{10}
\NormalTok{W}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 529940.1
\end{verbatim}

Sustituyendo en la fórmula:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{u }\OtherTok{\textless{}{-}}\NormalTok{ (C}\SpecialCharTok{*}\NormalTok{S)}\SpecialCharTok{/}\NormalTok{(C}\SpecialCharTok{*}\NormalTok{S }\SpecialCharTok{+}\NormalTok{ W)}
\NormalTok{u}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8333333
\end{verbatim}

\[ u \approx 0.83 \]

Esto significa que alrededor del \textbf{83\% de las hembras quedan
estériles}.

Finalmente, se ajusta la fecundidad del modelo reduciendo la tasa
original α:

\[ \alpha_{ef} = \alpha (1-u) \]

Como \(u=0.83\), queda:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha\_ef }\OtherTok{\textless{}{-}} \DecValTok{43} \SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ u)}
\NormalTok{alpha\_ef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.166667
\end{verbatim}

\[
\alpha_{\text{ajustado}} \approx 7.17 \; \text{huevos/día} \quad \text{con TIE (}u=0.83\text{)}.
\]

Tasa de Mortalidad del Adulto (\(\mu_A\))El parámetro \(\mu_A\) es el
inverso de la esperanza de vida promedio del adulto en la naturaleza.

\begin{itemize}
\tightlist
\item
  Vida de los Machos: \(14\) a \(21\) días (Promedio: \(17.5\) días)
\item
  Vida de las Hembras: \(10\) a \(30\) días (Promedio: \(20\) días)
\item
  Vida Promedio Ponderada (asumiendo 50\% machos, 50\%
  hembras):\[\text{Vida Promedio} \approx \frac{17.5 + 20}{2} = 18.75 \text{ días}\]
\end{itemize}

La tasa de mortalidad diaria (\(\mu_A\)) se calcula como el inverso del
tiempo promedio de
vida:\[\mu_A = \frac{1}{\text{Vida Promedio}} \approx \frac{1}{18.75} \approx 0.0533\]
Valor que usaremos para el modelo: \(\mu_A \approx 0.053\) por día

\begin{itemize}
\tightlist
\item
  Para estimar directamente los parámetros de tasas de transición
  (\(\eta, \kappa, \epsilon\)) para el ciclo de vida del parásito
  (\(H \rightarrow L \rightarrow P \rightarrow A\)). Usaremos la
  siguiente formula
\end{itemize}

\[\text{Tasa de Transición } (\lambda) = \frac{1}{\text{Tiempo Promedio de la Fase } (\tau \text{ días})}\]

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Parámetro}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Fase}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Duración Promedio (}\(\tau\))
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Tasa Diaria (}\(\lambda=1/\tau\))
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Valor que usaremos para el modelo}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\(\eta_{\text{base}}\) & Huevo \(\rightarrow\) Larva & 0.4167 días &
\(1 / 0.4167\) & 2.4 \\
\(\kappa_{\text{base}}\) & Larva \(\rightarrow\) Pupa & 6 días &
\(1 / 6\) & 0.167 \\
\(\epsilon_{\text{base}}\) & Pupa \(\rightarrow\) Adulto & 8.5 días &
\(1 / 8.5\) & 0.118 \\
\end{longtable}

\subsubsection{Parámetros del Compartimento Bovino
(SEIRS)}\label{paruxe1metros-del-compartimento-bovino-seirs}

Los parámetros del modelo SEIRS para bovinos se calculan utilizando
datos epidemiológicos del rebrote de miasis por \emph{Cochliomyia
hominivorax} en Chiapas durante 2024-2025, en combinación con
información biológica documentada por SENASICA.

\textbf{Notación de parámetros:}

\begin{itemize}
\tightlist
\item
  \(\sigma\): tasa de transición Susceptible → Expuesto (oviposición e
  incubación)
\item
  \(\beta\): tasa de transición Expuesto → Infestado (desarrollo
  larvario temprano)
\item
  \(\gamma\): tasa de transición Infestado → Recuperado (tratamiento y
  cicatrización)
\item
  \(\theta\): tasa de transición Recuperado → Susceptible (pérdida de
  protección)
\end{itemize}

\paragraph{Obtención de
Parámetros}\label{obtenciuxf3n-de-paruxe1metros-1}

Estos parámetros se basan en datos epidemiológicos oficiales de
SENASICA/INEGI.

Parámetro \(\sigma\) (Susceptible → Expuesto)

El parámetro \(\sigma\) representa la \textbf{tasa de incidencia},
calculada a partir de la proporción de casos observados durante el
período del brote.

\textbf{Paso 1: Cálculo de la proporción de incidencia}

La proporción de incidencia se calcula como la fracción de la población
bovina que fue infestada durante el período del brote:

\[\text{Proporción de incidencia} = \frac{\text{Casos confirmados}}{\text{Población total}}\]

\textbf{Datos:}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4583}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2917}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Valor}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Fuente}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Población bovina 2022 (Censo INEGI) & 1,653,718 cabezas & INEGI
(2022) \\
Tasa de crecimiento anual & 8.06\% & INEGI (2022) \\
Período de proyección & 2022 → 2025 (3 años) & - \\
Casos confirmados en Chiapas & 1,326 casos & SENASICA (2025) \\
\end{longtable}

\textbf{Cálculo de la población bovina en 2025:}

\[N_{2025} = N_{2022} \times (1 + r)^t\]

\[N_{2025} = 1,653,718 \times (1.0806)^3 = 1,653,718 \times 1.2617 = 2,086,688 \text{ cabezas}\]

\textbf{Cálculo de la proporción de incidencia:}

\[\text{Proporción} = \frac{1,326}{2,086,688} = 6.35 \times 10^{-4}\]

\textbf{Paso 2: Conversión a tasa de incidencia}

\[\sigma = \frac{\text{Proporción de incidencia}}{\text{Duración del brote (días)}}\]

\textbf{Datos temporales del brote:}

\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
& \textbf{Valor} & \textbf{Fuente} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Inicio del brote & Noviembre 2024 & SENASICA (2024) \\
Casos reportados hasta & 24 de noviembre 2025 & SENASICA (2025) \\
Duración del brote & \textbf{365 días} & Calculado \\
\end{longtable}

\textbf{Cálculo de} \(\sigma\) \textbf{(tasa de incidencia):}

\[\sigma = \frac{6.35 \times 10^{-4}}{365 \text{ días}} = 1.74 \times 10^{-6} \text{ día}^{-1}\]

\textbf{Valor que usaremos para el modelo:}
\(\sigma \approx 1.74 \times 10^{-6}\) día\(^{-1}\) (0.00000174
día\(^{-1}\) )

Parámetro \(\beta\) (Expuesto → Infestado)

El parámetro \(\beta\) representa la tasa a la cual bovinos con huevos
depositados o larvas recién eclosionadas desarrollan una infestación
clínicamente detectable.

\textbf{Base biológica (SENASICA, 2020):} Entre 12 y 24 horas después de
la oviposición las larvas eclosionan y se alimentan de tejido vivo
durante 4 a 8 días.

\textbf{Componentes del estado Expuesto (E):}

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
\textbf{Fase} & \textbf{Duración} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Huevos (pre-eclosión) & 12-24h (promedio 18h) \\
Larvas recién nacidas & 24-32h (promedio 30h) \\
\textbf{Total en estado E} & \textbf{\textasciitilde2 días (48 h)} \\
\end{longtable}

\[\text{Tasa de Transición } (\beta) = \frac{1}{\text{Tiempo Promedio en E } (\tau_E \text{ días})}\]

\[\beta = \frac{1}{2 \text{ días}} = 0.5 \text{ día}^{-1}\]

\textbf{Valor que usaremos para el modelo:} \(\beta \approx 0.5\)
día\(^{-1}\)

\paragraph{\texorpdfstring{Parámetro \(\gamma\) (Infestado →
Recuperado)}{Parámetro \textbackslash gamma (Infestado → Recuperado)}}\label{paruxe1metro-gamma-infestado-recuperado}

El parámetro \(\gamma\) representa la tasa a la cual bovinos infestados
se recuperan tras eliminación natural de larvas.

\textbf{Base biológica:}

\begin{itemize}
\tightlist
\item
  \textbf{Sin tratamiento:} La miasis puede ser fatal en 7-10 días
\end{itemize}

\textbf{Cálculo:}

\[\tau_{\text{recuperación}} = 7 \text{ días}\]

\[\gamma = \frac{1}{\tau_{\text{recuperación}}} = \frac{1}{7} \approx 0.143 \text{ día}^{-1}\]

\textbf{Valor que usaremos para el modelo:} \(\gamma \approx 0.14\)
día\(^{-1}\)

\subsection{Referencias}\label{referencias}

\begin{itemize}
\tightlist
\item
  Servicio Nacional de Sanidad, Inocuidad y Calidad Agroalimentaria
  {[}SENASICA{]}. (2020). Todo lo que usted debe saber sobre la
  erradicación de la miasis causada por el gusano barrenador del ganado
  (GBG).
  \url{https://www.gob.mx/cms/uploads/attachment/file/936256/TODO_LO_QUE_DEBES_SABER_SOBRE_LA_ERRADICACI_N_DE_LA_MIASIS_CAUSADA_POR_GBG.pdf}
\end{itemize}

\end{document}
